# Generated by Django 2.2.7 on 2020-02-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='parent_asset_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='video_url',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('uid', 'asset_id')},
        ),
    ]
