# Generated by Django 2.2.7 on 2020-02-16 11:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0002_auto_20200216_1104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('uid', 'asset_id')},
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ott.Asset')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ott.User')),
            ],
        ),
    ]
