# Generated by Django 2.2.7 on 2020-02-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0003_auto_20200216_1113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
    ]
