# Generated by Django 2.2.7 on 2020-02-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0004_auto_20200216_1115'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('uid', 'asset_id')},
        ),
    ]
