# Generated by Django 2.2.7 on 2020-02-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0005_auto_20200217_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='id',
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
